FROM rust:1.78
WORKDIR /app
RUN rustup component add rustfmt
RUN cargo install cargo-watch cargo-make
# RUN mkdir -p -m 0700 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
# RUN touch ~/.ssh/config
# RUN chown -R root:$USER ~/.ssh/
# RUN chmod -R 600 ~/.ssh/
# RUN --mount=type=ssh

